/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

import controlador.ControladorListarPersonas;
import javax.swing.JTable;
import modelo.GestionConexion;


public class ListarPersona extends javax.swing.JFrame {
    private ControladorListarPersonas control;
    private GestionConexion conexion;
    private AltaDomicilio domic;
    /**
     * Creates new form ListarPersona
     */
    public ListarPersona(GestionConexion conn, ControladorListarPersonas p,AltaDomicilio dom) {
        initComponents();
        conexion = conn;
        control = p;
        domic=dom;
    }

    public JTable getTb_Person() {
        return tb_Person;
    }

    public void setTb_Person(JTable tb_Person) {
        this.tb_Person = tb_Person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_buscarPer = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Person = new javax.swing.JTable();
        btn_AcepPerson = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        btn_BuscarPersona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elija Persona:");

        cmb_buscarPer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empleado", "Cliente", "Proveedor" }));

        tb_Person.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_Person);

        btn_AcepPerson.setText("Aceptar");
        btn_AcepPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AcepPersonActionPerformed(evt);
            }
        });

        btn_Exit.setText("Salir");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        btn_BuscarPersona.setText("Buscar");
        btn_BuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_buscarPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_BuscarPersona)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btn_AcepPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_buscarPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BuscarPersona))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AcepPerson)
                    .addComponent(btn_Exit))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarPersonaActionPerformed
        String persona = cmb_buscarPer.getSelectedItem().toString();
        control.listarpersonas(persona);
    }//GEN-LAST:event_btn_BuscarPersonaActionPerformed

    private void btn_AcepPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AcepPersonActionPerformed
        String persona = cmb_buscarPer.getSelectedItem().toString();
        String id=control.obtenerID(persona);
        domic.getTxt_person().setText(id);
    }//GEN-LAST:event_btn_AcepPersonActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AcepPerson;
    private javax.swing.JButton btn_BuscarPersona;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JComboBox cmb_buscarPer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_Person;
    // End of variables declaration//GEN-END:variables
}
