/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Cliente;
import controlador.ControladorCliente;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.GestionConexion;

/**
 *
 * @author Mariana
 */
public class ModCliente extends javax.swing.JFrame {

    private GestionConexion conn;
    private Cliente cliente;
    private ControladorCliente controlcli;

    public ModCliente(GestionConexion conn, Cliente cliente, ControladorCliente controlcli) {
        this.conn = conn;
        this.cliente = cliente;
        this.controlcli = controlcli;
        initComponents();
        this.setLocationRelativeTo(null);
        controlcli.modificarCliente(this);
    }

   
    /**
     * Creates new form ModCliente
     */
  
     public void limpiar() {
        txt_idmod.setText(null);
        txtnom_mod.setText(null);
        txtap_mod.setText(null);
        txtdni_mod.setText(null);
        txtcuil_mod.setText(null);
        txtdir_mod.setText(null);
        txttelefono_mod.setText(null);
        txt_email_mod.setText(null);
        
    }
     
     

    public JComboBox getjComboBox_tipoCliente_mod() {
        return jComboBox_tipoCliente_mod;
    }

    public void setjComboBox_tipoCliente_mod(JComboBox jComboBox_tipoCliente_mod) {
        this.jComboBox_tipoCliente_mod = jComboBox_tipoCliente_mod;
    }

    public JTextField getTxt_email_mod() {
        return txt_email_mod;
    }

    public void setTxt_email_mod(JTextField txt_email_mod) {
        this.txt_email_mod = txt_email_mod;
    }

    public JTextField getTxtap_mod() {
        return txtap_mod;
    }

    public void setTxtap_mod(JTextField txtap_mod) {
        this.txtap_mod = txtap_mod;
    }

    public JTextField getTxtcuil_mod() {
        return txtcuil_mod;
    }

    public void setTxtcuil_mod(JTextField txtcuil_mod) {
        this.txtcuil_mod = txtcuil_mod;
    }

    public JTextField getTxtdir_mod() {
        return txtdir_mod;
    }

    public void setTxtdir_mod(JTextField txtdir_mod) {
        this.txtdir_mod = txtdir_mod;
    }

    public JTextField getTxtdni_mod() {
        return txtdni_mod;
    }

    public void setTxtdni_mod(JTextField txtdni_mod) {
        this.txtdni_mod = txtdni_mod;
    }

    public JTextField getTxtnom_mod() {
        return txtnom_mod;
    }

    public void setTxtnom_mod(JTextField txtnom_mod) {
        this.txtnom_mod = txtnom_mod;
    }

    public JTextField getTxttelefono_mod() {
        return txttelefono_mod;
    }

    public void setTxttelefono_mod(JTextField txttelefono_mod) {
        this.txttelefono_mod = txttelefono_mod;
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar_mod = new javax.swing.JButton();
        txttelefono_mod = new javax.swing.JTextField();
        txt_idmod = new javax.swing.JTextField();
        txt_email_mod = new javax.swing.JTextField();
        lblidcliente = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lbl_tipo = new javax.swing.JLabel();
        jComboBox_tipoCliente_mod = new javax.swing.JComboBox();
        lblnomyap = new javax.swing.JLabel();
        lbldni = new javax.swing.JLabel();
        lblcuil = new javax.swing.JLabel();
        lbldir = new javax.swing.JLabel();
        txtnom_mod = new javax.swing.JTextField();
        txtap_mod = new javax.swing.JTextField();
        txtdni_mod = new javax.swing.JTextField();
        txtcuil_mod = new javax.swing.JTextField();
        txtdir_mod = new javax.swing.JTextField();
        btnCancelar_mod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAceptar_mod.setText("Aceptar");
        btnAceptar_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar_modActionPerformed(evt);
            }
        });

        txt_idmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idmodActionPerformed(evt);
            }
        });

        lblidcliente.setText("Identificador");

        lbltelefono.setText("Teléfono");

        lblemail.setText("email");

        lbl_tipo.setText("Tipo");

        jComboBox_tipoCliente_mod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mayorista", "Minorista", "Cuenta Corriente", " " }));

        lblnomyap.setText("Nombre y Apellido ");

        lbldni.setText("Dni");

        lblcuil.setText("Cuil");

        lbldir.setText("Dirección");

        txtnom_mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnom_modKeyTyped(evt);
            }
        });

        txtap_mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtap_modKeyTyped(evt);
            }
        });

        txtdni_mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdni_modKeyTyped(evt);
            }
        });

        txtcuil_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcuil_modActionPerformed(evt);
            }
        });

        btnCancelar_mod.setText("Cancelar");
        btnCancelar_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_modActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblcuil)
                                .addGap(18, 18, 18)
                                .addComponent(txtcuil_mod))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbldni)
                                .addGap(18, 18, 18)
                                .addComponent(txtdni_mod))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnomyap)
                                    .addComponent(lblidcliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_idmod, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnom_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtap_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbldir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdir_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tipo)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox_tipoCliente_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(btnAceptar_mod)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar_mod))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lbltelefono)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txttelefono_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblemail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_email_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idmod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblidcliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnomyap)
                    .addComponent(txtnom_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtap_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldni)
                    .addComponent(txtdni_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcuil)
                    .addComponent(txtcuil_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldir)
                    .addComponent(txtdir_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefono)
                    .addComponent(lblemail)
                    .addComponent(txt_email_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefono_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipo)
                    .addComponent(jComboBox_tipoCliente_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar_mod)
                    .addComponent(btnCancelar_mod))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptar_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar_modActionPerformed
        // TODO add your handling code here:
        cliente.setIdCliente(Integer.valueOf(txt_idmod.getText()));
        cliente.setNombre(txtnom_mod.getText());
        cliente.setApellido(txtap_mod.getText());
        cliente.setDni(Integer.valueOf(txtdni_mod.getText()));
        cliente.setCuil(Integer.valueOf(txtcuil_mod.getText()));
        cliente.setDireccion(txtdir_mod.getText());
        cliente.setTelefono(Integer.valueOf(txttelefono_mod.getText()));
        cliente.setEmail(txt_email_mod.getText());
        cliente.setTipo(jComboBox_tipoCliente_mod.getSelectedItem().toString());
      
         controlcli.updateCliente(cliente);
        controlcli.mostrarClientes();
        this.dispose();

    }//GEN-LAST:event_btnAceptar_modActionPerformed

    private void txt_idmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idmodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idmodActionPerformed

    private void txtnom_modKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnom_modKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
            && (car != (char) KeyEvent.VK_SPACE) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            JOptionPane.showMessageDialog(this, "Ingrese solo letras");
            evt.consume();
        }
    }//GEN-LAST:event_txtnom_modKeyTyped

    private void txtap_modKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtap_modKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
            && (car != (char) KeyEvent.VK_SPACE) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            JOptionPane.showMessageDialog(this, "Ingrese solo letras");
            evt.consume();
        }
    }//GEN-LAST:event_txtap_modKeyTyped

    private void txtdni_modKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdni_modKeyTyped
        /*   char car = evt.getKeyChar();
        if (txtdni.getText().length() >= 9) {
            JOptionPane.showMessageDialog(this, "Permitido hasta 9 digitos");
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            JOptionPane.showMessageDialog(this, "Ingrese solo números");
            evt.consume();
        }*/
    }//GEN-LAST:event_txtdni_modKeyTyped

    private void txtcuil_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcuil_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcuil_modActionPerformed

    private void btnCancelar_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_modActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnCancelar_modActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar_mod;
    private javax.swing.JButton btnCancelar_mod;
    public javax.swing.JComboBox jComboBox_tipoCliente_mod;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lblcuil;
    private javax.swing.JLabel lbldir;
    private javax.swing.JLabel lbldni;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblidcliente;
    private javax.swing.JLabel lblnomyap;
    private javax.swing.JLabel lbltelefono;
    public javax.swing.JTextField txt_email_mod;
    public javax.swing.JTextField txt_idmod;
    public javax.swing.JTextField txtap_mod;
    public javax.swing.JTextField txtcuil_mod;
    public javax.swing.JTextField txtdir_mod;
    public javax.swing.JTextField txtdni_mod;
    public javax.swing.JTextField txtnom_mod;
    public javax.swing.JTextField txttelefono_mod;
    // End of variables declaration//GEN-END:variables
}
