/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import modelo.Cliente;
import controlador.ControladorCliente;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.GestionConexion;

/**
 *
 * @author Mariana
 */
public class ModCliente extends javax.swing.JFrame {

    private GestionConexion conn;
    private Cliente cliente;
    private ControladorCliente controlcli;

    public ModCliente(GestionConexion conn, Cliente cliente, ControladorCliente controlcli) {
        this.conn = conn;
        this.cliente = cliente;
        this.controlcli = controlcli;
        initComponents();
        this.setLocationRelativeTo(null);
        controlcli.modificarCliente(this);
    }

   
    /**
     * Creates new form ModCliente
     */
  
     public void limpiar() {
        txt_idmod.setText(null);
        txtnom_mod.setText(null);
        txtap_mod.setText(null);
        txtdni_mod.setText(null);
        txtcuil_mod.setText(null);
        txttelefono_mod.setText(null);
        txt_email_mod.setText(null);
        
    }
     
     

    public JComboBox getjComboBox_tipoCliente_mod() {
        return jComboBox_tipoCliente_mod;
    }

    public void setjComboBox_tipoCliente_mod(JComboBox jComboBox_tipoCliente_mod) {
        this.jComboBox_tipoCliente_mod = jComboBox_tipoCliente_mod;
    }

    public JTextField getTxt_email_mod() {
        return txt_email_mod;
    }

    public void setTxt_email_mod(JTextField txt_email_mod) {
        this.txt_email_mod = txt_email_mod;
    }

    public JTextField getTxtap_mod() {
        return txtap_mod;
    }

    public void setTxtap_mod(JTextField txtap_mod) {
        this.txtap_mod = txtap_mod;
    }

    public JTextField getTxtcuil_mod() {
        return txtcuil_mod;
    }

    public void setTxtcuil_mod(JTextField txtcuil_mod) {
        this.txtcuil_mod = txtcuil_mod;
    }

    public JTextField getTxtdni_mod() {
        return txtdni_mod;
    }

    public void setTxtdni_mod(JTextField txtdni_mod) {
        this.txtdni_mod = txtdni_mod;
    }

    public JTextField getTxtnom_mod() {
        return txtnom_mod;
    }

    public void setTxtnom_mod(JTextField txtnom_mod) {
        this.txtnom_mod = txtnom_mod;
    }

    public JTextField getTxttelefono_mod() {
        return txttelefono_mod;
    }

    public void setTxttelefono_mod(JTextField txttelefono_mod) {
        this.txttelefono_mod = txttelefono_mod;
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar_mod = new javax.swing.JButton();
        txttelefono_mod = new javax.swing.JTextField();
        txt_idmod = new javax.swing.JTextField();
        txt_email_mod = new javax.swing.JTextField();
        lblidcliente = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lbl_tipo = new javax.swing.JLabel();
        jComboBox_tipoCliente_mod = new javax.swing.JComboBox();
        lblnomyap = new javax.swing.JLabel();
        lbldni = new javax.swing.JLabel();
        lblcuil = new javax.swing.JLabel();
        txtnom_mod = new javax.swing.JTextField();
        txtap_mod = new javax.swing.JTextField();
        txtdni_mod = new javax.swing.JTextField();
        txtcuil_mod = new javax.swing.JTextField();
        btnCancelar_mod = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificacion de Cliente");
        setResizable(false);

        btnAceptar_mod.setText("Aceptar");
        btnAceptar_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar_modActionPerformed(evt);
            }
        });

        txttelefono_mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefono_modKeyTyped(evt);
            }
        });

        txt_idmod.setEnabled(false);
        txt_idmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idmodActionPerformed(evt);
            }
        });

        lblidcliente.setText("Identificador");

        lbltelefono.setText("Teléfono");

        lblemail.setText("Email");

        lbl_tipo.setText("Tipo");

        jComboBox_tipoCliente_mod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mayorista", "Minorista", "Cuenta Corriente", " " }));

        lblnomyap.setText("Nombre");

        lbldni.setText("Dni");

        lblcuil.setText("Cuil");

        txtnom_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnom_modActionPerformed(evt);
            }
        });
        txtnom_mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnom_modKeyTyped(evt);
            }
        });

        txtap_mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtap_modKeyTyped(evt);
            }
        });

        txtdni_mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdni_modKeyTyped(evt);
            }
        });

        txtcuil_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcuil_modActionPerformed(evt);
            }
        });
        txtcuil_mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcuil_modKeyTyped(evt);
            }
        });

        btnCancelar_mod.setText("Cancelar");
        btnCancelar_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_modActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Apellido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbltelefono)
                                            .addComponent(lbl_tipo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                                        .addComponent(txt_email_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblnomyap)
                                            .addComponent(lblidcliente))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_idmod, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtnom_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(lblcuil)
                                                    .addComponent(lblemail))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtcuil_mod, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                                    .addComponent(txtap_mod))))))
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbldni)
                                        .addGap(50, 50, 50)
                                        .addComponent(txtdni_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox_tipoCliente_mod, javax.swing.GroupLayout.Alignment.TRAILING, 0, 145, Short.MAX_VALUE)
                                        .addComponent(txttelefono_mod, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnAceptar_mod)
                        .addGap(63, 63, 63)
                        .addComponent(btnCancelar_mod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idmod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblidcliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnomyap)
                    .addComponent(txtnom_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtap_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldni)
                    .addComponent(txtdni_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcuil_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcuil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefono)
                    .addComponent(lblemail)
                    .addComponent(txt_email_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefono_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tipo)
                    .addComponent(jComboBox_tipoCliente_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar_mod)
                    .addComponent(btnAceptar_mod)
                    .addComponent(btnSalir))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptar_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar_modActionPerformed
        // TODO add your handling code here:
        cliente.setIdCliente(Integer.valueOf(txt_idmod.getText()));
        cliente.setNombre(txtnom_mod.getText());
        cliente.setApellido(txtap_mod.getText());
        cliente.setDni(Integer.valueOf(txtdni_mod.getText()));
        cliente.setCuil(Integer.valueOf(txtcuil_mod.getText()));
        cliente.setTelefono(Integer.valueOf(txttelefono_mod.getText()));
        cliente.setEmail(txt_email_mod.getText());
        cliente.setTipo(jComboBox_tipoCliente_mod.getSelectedItem().toString());
      
         controlcli.updateCliente(cliente);
        controlcli.mostrarClientes();
        this.dispose();

    }//GEN-LAST:event_btnAceptar_modActionPerformed

    private void txt_idmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idmodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idmodActionPerformed

    private void txtnom_modKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnom_modKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
            && (car != (char) KeyEvent.VK_SPACE) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            JOptionPane.showMessageDialog(this, "Ingrese solo letras");
            evt.consume();
        }
    }//GEN-LAST:event_txtnom_modKeyTyped

    private void txtap_modKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtap_modKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
            && (car != (char) KeyEvent.VK_SPACE) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            JOptionPane.showMessageDialog(this, "Ingrese solo letras");
            evt.consume();
        }
    }//GEN-LAST:event_txtap_modKeyTyped

    private void txtdni_modKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdni_modKeyTyped
         char car = evt.getKeyChar();
        if (txtdni_mod.getText().length() >= 9) {
            JOptionPane.showMessageDialog(this, "Permitido hasta 9 digitos");
            evt.consume();
        }
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            JOptionPane.showMessageDialog(this, "Ingrese solo números");
            evt.consume();
        }
    }//GEN-LAST:event_txtdni_modKeyTyped

    private void txtcuil_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcuil_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcuil_modActionPerformed

    private void btnCancelar_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_modActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnCancelar_modActionPerformed

    private void txtcuil_modKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcuil_modKeyTyped
         char car = evt.getKeyChar();
        if (txtcuil_mod.getText().length() >= 9) {
            JOptionPane.showMessageDialog(this, "Permitido hasta 9 digitos");
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            JOptionPane.showMessageDialog(this, "Ingrese solo números");
            evt.consume();
        }
    }//GEN-LAST:event_txtcuil_modKeyTyped

    private void txttelefono_modKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefono_modKeyTyped
         char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            JOptionPane.showMessageDialog(this, "Ingrese solo números");
            evt.consume();
        }
    }//GEN-LAST:event_txttelefono_modKeyTyped

    private void txtnom_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnom_modActionPerformed
    
    }//GEN-LAST:event_txtnom_modActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar_mod;
    private javax.swing.JButton btnCancelar_mod;
    private javax.swing.JButton btnSalir;
    public javax.swing.JComboBox jComboBox_tipoCliente_mod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lblcuil;
    private javax.swing.JLabel lbldni;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblidcliente;
    private javax.swing.JLabel lblnomyap;
    private javax.swing.JLabel lbltelefono;
    public javax.swing.JTextField txt_email_mod;
    public javax.swing.JTextField txt_idmod;
    public javax.swing.JTextField txtap_mod;
    public javax.swing.JTextField txtcuil_mod;
    public javax.swing.JTextField txtdni_mod;
    public javax.swing.JTextField txtnom_mod;
    public javax.swing.JTextField txttelefono_mod;
    // End of variables declaration//GEN-END:variables
}
