/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import modelo.GestionConexion;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Martin
 */
public class ModPass extends javax.swing.JFrame {

    private GestionConexion conexion;
    private String user;

    /**
     * Creates new form ModPass
     */
    public ModPass(GestionConexion conn, String usr) {
        conexion = conn;
        user = usr;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_OldPass = new javax.swing.JPasswordField();
        txt_NewPass = new javax.swing.JPasswordField();
        txt_NewCpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Change = new javax.swing.JButton();
        btn_out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cambio de Contraseña");

        jLabel1.setText("Ingrese Contraseña:");

        jLabel2.setText("Ingrese Nueva Contraseña:");

        jLabel3.setText("Confirmar Nueva Contraseña:");

        btn_Change.setText("Cambiar Contraseña");
        btn_Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangeActionPerformed(evt);
            }
        });

        btn_out.setText("Salir");
        btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(btn_Change))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_OldPass)
                    .addComponent(txt_NewPass)
                    .addComponent(txt_NewCpass)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(btn_out, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_OldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NewCpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Change)
                    .addComponent(btn_out))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPasswordField getTxt_NewCpass() {
        return txt_NewCpass;
    }

    public void setTxt_NewCpass(JPasswordField txt_NewCpass) {
        this.txt_NewCpass = txt_NewCpass;
    }

    public JPasswordField getTxt_NewPass() {
        return txt_NewPass;
    }

    public void setTxt_NewPass(JPasswordField txt_NewPass) {
        this.txt_NewPass = txt_NewPass;
    }

    public JPasswordField getTxt_OldPass() {
        return txt_OldPass;
    }

    public void setTxt_OldPass(JPasswordField txt_OldPass) {
        this.txt_OldPass = txt_OldPass;
    }

    private void btn_ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangeActionPerformed
        try {
            
            String oldPass = DigestUtils.md5Hex(txt_OldPass.getText());
            
            String newPass = DigestUtils.md5Hex(txt_NewPass.getText());
            
            String newCpass =DigestUtils.md5Hex(txt_NewCpass.getText());
            String pass="";
            String sql = "SELECT pass FROM  empleado where user='" + user + "';";
            
            Statement st = conexion.getStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                pass = rs.getString("pass");

            }
            if (pass.equals(oldPass)) {
                if (newPass.equals(newCpass)) {
                    String query = "UPDATE empleado SET pass='" + newCpass + "' where user='"+user+"' ;";
                    try {

                        st.executeUpdate(query);
                        JOptionPane.showMessageDialog(null, "Se ha cambiado su contraseña correctamente"); 
                    } catch (Exception e) {
                    }
                }
                else{
                JOptionPane.showMessageDialog(null, "Las contraseñas ingresadas no coinciden");
                }
            }
            else{
            JOptionPane.showMessageDialog(null, "Introduzca su contraseña nuevamente");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModPass.class.getName()).log(Level.SEVERE, null, ex);
        }

       
       this.dispose();
    }//GEN-LAST:event_btn_ChangeActionPerformed

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_outActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Change;
    private javax.swing.JButton btn_out;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txt_NewCpass;
    private javax.swing.JPasswordField txt_NewPass;
    private javax.swing.JPasswordField txt_OldPass;
    // End of variables declaration//GEN-END:variables
}
