/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.BuscarProducto;
import controlador.ControladorProducto;
import controlador.ControladorUsuario;
import controlador.ControladorCliente;
import controlador.ControladorProveedor;
import controlador.ControladorVenta;
import modelo.GestionConexion;

/**
 *
 * @author martinrh83
 */
public class PrincipalEmpleado extends javax.swing.JFrame {

    private GestionConexion conexion;
    
    public PrincipalEmpleado(GestionConexion c) {
        conexion=c;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        laber_usuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProducto = new javax.swing.JMenu();
        menuItAltaProd = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenu();
        menuItNvaVenta = new javax.swing.JMenuItem();
        menuItListVenta = new javax.swing.JMenuItem();
        menuCompra = new javax.swing.JMenu();
        menuItNvaCpra = new javax.swing.JMenuItem();
        menuItNvaPedCpra = new javax.swing.JMenuItem();
        menuItListMCpra = new javax.swing.JMenuItem();

        jMenuItem20.setText("jMenuItem20");

        jMenuItem24.setText("jMenuItem24");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        menuProducto.setText("Producto");

        menuItAltaProd.setLabel("Alta");
        menuItAltaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItAltaProdActionPerformed(evt);
            }
        });
        menuProducto.add(menuItAltaProd);

        jMenuItem1.setText("Buscar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuProducto.add(jMenuItem1);

        jMenuBar1.add(menuProducto);

        menuVenta.setText("Venta");

        menuItNvaVenta.setText("Nueva");
        menuItNvaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItNvaVentaActionPerformed(evt);
            }
        });
        menuVenta.add(menuItNvaVenta);

        menuItListVenta.setText("Listado");
        menuVenta.add(menuItListVenta);

        jMenuBar1.add(menuVenta);

        menuCompra.setText("Compra");

        menuItNvaCpra.setText("Nueva");
        menuCompra.add(menuItNvaCpra);

        menuItNvaPedCpra.setText("Nuevo Pedido");
        menuCompra.add(menuItNvaPedCpra);

        menuItListMCpra.setText("Listado Mes");
        menuCompra.add(menuItListMCpra);

        jMenuBar1.add(menuCompra);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laber_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 364, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 249, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laber_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItAltaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItAltaProdActionPerformed
       ControladorProducto contAlta= new ControladorProducto(conexion);
       
    }//GEN-LAST:event_menuItAltaProdActionPerformed

    private void menuItNvaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItNvaVentaActionPerformed
        String user=laber_usuario.getText();
        ControladorVenta venta = new ControladorVenta (conexion,user);
        
    }
    /*
        windowNewVenta.setVisible(true);    }//GEN-LAST:event_menuItNvaVentaActionPerformed
*/
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        BuscarProducto search= new BuscarProducto(conexion);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem24;
    public javax.swing.JLabel laber_usuario;
    private javax.swing.JMenu menuCompra;
    private javax.swing.JMenuItem menuItAltaProd;
    private javax.swing.JMenuItem menuItListMCpra;
    private javax.swing.JMenuItem menuItListVenta;
    private javax.swing.JMenuItem menuItNvaCpra;
    private javax.swing.JMenuItem menuItNvaPedCpra;
    private javax.swing.JMenuItem menuItNvaVenta;
    private javax.swing.JMenu menuProducto;
    private javax.swing.JMenu menuVenta;
    // End of variables declaration//GEN-END:variables
}
